# Generated by Django 5.0.6 on 2024-07-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_profile_profile_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_class',
            name='firstname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile_class',
            name='lastname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
