# Generated by Django 5.0.6 on 2024-07-08 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_profile_class_firstname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_class',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile_class',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile_class',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='profile_class',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_class',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
