# Generated by Django 5.0.6 on 2024-07-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile_firstname_profile_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phonenumber',
        ),
    ]
