# Generated by Django 5.0.6 on 2024-07-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_profile_address_line_profile_country_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
