# Generated by Django 5.0.6 on 2024-07-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='pics',
            field=models.ImageField(default='D:\\loginweb\\websiteme\\static\\defaulthoouse\\defhouse.jpg', upload_to='property_images/'),
            preserve_default=False,
        ),
    ]
