# Generated by Django 5.0.6 on 2024-07-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_house_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='pics',
            field=models.ImageField(default='property_images/defhouse.jpg', upload_to='property_images/'),
        ),
    ]
