# Generated by Django 5.0.6 on 2024-07-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_house_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
