# Generated by Django 5.0.6 on 2024-07-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pro_pic',
            field=models.ImageField(default='../static/profilepic/default.png', upload_to='../static/profilepic/'),
        ),
    ]
