# Generated by Django 5.0.6 on 2024-07-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_house_bathrooms_house_bedrooms_house_default_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='house',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='house',
            name='sqft',
        ),
        migrations.RemoveField(
            model_name='house',
            name='utilities',
        ),
        migrations.AddField(
            model_name='house',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='balcony',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='bathrooms_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='bedrooms_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='contact_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='cooling_type',
            field=models.CharField(choices=[('central', 'Central Air'), ('window', 'Window Units'), ('none', 'No Cooling')], default='central', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='furnishing_status',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished')], default='furnished', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='garden',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='heating_type',
            field=models.CharField(choices=[('central', 'Central Heating'), ('electric', 'Electric Heating'), ('none', 'No Heating')], default='central', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='nearby_amenities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='parking_spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='pet_policy',
            field=models.CharField(choices=[('allowed', 'Pets Allowed'), ('not_allowed', 'No Pets Allowed')], default='allowed', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='pool',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('commercial', 'Commercial')], default='apartment', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='rooms_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='security_features',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('sold', 'Sold')], default='for_rent', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='year_built',
            field=models.IntegerField(default=2015),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
