# Generated by Django 5.0.6 on 2024-07-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_house_bathrooms_remove_house_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='year_built',
            field=models.IntegerField(null=True),
        ),
    ]
